<?php

return [
    'AccountFiscalPosition' => Sefirosweb\LaravelOdooConnector\Http\Models\AccountFiscalPosition::class,
    'AccountMove' => Sefirosweb\LaravelOdooConnector\Http\Models\AccountMove::class,
    'AccountMoveLine' => Sefirosweb\LaravelOdooConnector\Http\Models\AccountMoveLine::class,
    'AccountPaymentMode' => Sefirosweb\LaravelOdooConnector\Http\Models\AccountPaymentMode::class,
    'AccountPaymentTerm' => Sefirosweb\LaravelOdooConnector\Http\Models\AccountPaymentTerm::class,
    'AccountTax' => Sefirosweb\LaravelOdooConnector\Http\Models\AccountTax::class,
    'CrmTeam' => Sefirosweb\LaravelOdooConnector\Http\Models\CrmTeam::class,
    'IrModel' => Sefirosweb\LaravelOdooConnector\Http\Models\IrModel::class,
    'MailActivity' => Sefirosweb\LaravelOdooConnector\Http\Models\MailActivity::class,
    'MrpBom' => Sefirosweb\LaravelOdooConnector\Http\Models\MrpBom::class,
    'MrpBomLine' => Sefirosweb\LaravelOdooConnector\Http\Models\MrpBomLine::class,
    'MrpImmediateProduction' => Sefirosweb\LaravelOdooConnector\Http\Models\MrpImmediateProduction::class,
    'MrpImmediateProductionLine' => Sefirosweb\LaravelOdooConnector\Http\Models\MrpImmediateProductionLine::class,
    'MrpProduction' => Sefirosweb\LaravelOdooConnector\Http\Models\MrpProduction::class,
    'OdooModel' => Sefirosweb\LaravelOdooConnector\Http\Models\OdooModel::class,
    'ProductAttribute' => Sefirosweb\LaravelOdooConnector\Http\Models\ProductAttribute::class,
    'ProductAttributeValue' => Sefirosweb\LaravelOdooConnector\Http\Models\ProductAttributeValue::class,
    'ProductProduct' => Sefirosweb\LaravelOdooConnector\Http\Models\ProductProduct::class,
    'ProductSupplierinfo' => Sefirosweb\LaravelOdooConnector\Http\Models\ProductSupplierinfo::class,
    'ProductTemplate' => Sefirosweb\LaravelOdooConnector\Http\Models\ProductTemplate::class,
    'ProductTemplateAttributeLine' => Sefirosweb\LaravelOdooConnector\Http\Models\ProductTemplateAttributeLine::class,
    'PurchaseOrder' => Sefirosweb\LaravelOdooConnector\Http\Models\PurchaseOrder::class,
    'PurchaseOrderLine' => Sefirosweb\LaravelOdooConnector\Http\Models\PurchaseOrderLine::class,
    'ResCountry' => Sefirosweb\LaravelOdooConnector\Http\Models\ResCountry::class,
    'ResLang' => Sefirosweb\LaravelOdooConnector\Http\Models\ResLang::class,
    'ResPartner' => Sefirosweb\LaravelOdooConnector\Http\Models\ResPartner::class,
    'ResUser' => Sefirosweb\LaravelOdooConnector\Http\Models\ResUser::class,
    'SaleOrder' => Sefirosweb\LaravelOdooConnector\Http\Models\SaleOrder::class,
    'SaleOrderLine' => Sefirosweb\LaravelOdooConnector\Http\Models\SaleOrderLine::class,
    'StockLocation' => Sefirosweb\LaravelOdooConnector\Http\Models\StockLocation::class,
    'StockMove' => Sefirosweb\LaravelOdooConnector\Http\Models\StockMove::class,
    'StockMoveLine' => Sefirosweb\LaravelOdooConnector\Http\Models\StockMoveLine::class,
    'StockPicking' => Sefirosweb\LaravelOdooConnector\Http\Models\StockPicking::class,
    'StockPickingType' => Sefirosweb\LaravelOdooConnector\Http\Models\StockPickingType::class,
    'StockQuant' => Sefirosweb\LaravelOdooConnector\Http\Models\StockQuant::class,
    'StockRoute' => Sefirosweb\LaravelOdooConnector\Http\Models\StockRoute::class,
    'UomUom' => Sefirosweb\LaravelOdooConnector\Http\Models\UomUom::class,
];
